const EXERCISE_MUSCLES = {
  'Barbell Bench Press':        ['chest', 'front_delts', 'triceps'],
  'Bench Press':                ['chest', 'front_delts', 'triceps'],
  'Dumbbell Bench Press':       ['chest', 'front_delts', 'triceps'],
  'Incline Bench Press':        ['chest', 'front_delts', 'triceps'],
  'Incline Dumbbell Press':     ['chest', 'front_delts', 'triceps'],
  'Cable Chest Fly':            ['chest', 'front_delts'],
  'Cable Fly':                  ['chest', 'front_delts'],
  'Dumbbell Fly':               ['chest', 'front_delts'],
  'Pec Deck':                   ['chest', 'front_delts'],
  'Push Up':                    ['chest', 'front_delts', 'triceps'],
  'Overhead Press':             ['front_delts', 'triceps'],
  'Overhead Barbell Press':     ['front_delts', 'triceps'],
  'Military Press':             ['front_delts', 'triceps'],
  'Dumbbell Shoulder Press':    ['front_delts', 'triceps'],
  'Overhead Dumbbell Press':    ['front_delts', 'triceps'],
  'Seated Dumbbell Press':      ['front_delts', 'triceps'],
  'Seated Barbell Press':       ['front_delts', 'triceps'],
  'Machine Shoulder Press':     ['front_delts', 'triceps'],
  'Arnold Press':               ['front_delts', 'rear_delts', 'triceps'],
  'Lateral Raise':              ['front_delts', 'rear_delts'],
  'Cable Lateral Raises':       ['front_delts', 'rear_delts'],
  'Front Raise':                ['front_delts'],
  'Dumbbell Front Raise':       ['front_delts'],
  'Face Pull':                  ['rear_delts', 'traps'],
  'Reverse Fly':                ['rear_delts', 'traps'],
  'Dumbbell Reverse Fly':       ['rear_delts', 'traps'],
  'Pull Up':                    ['back', 'biceps'],
  'Lat Pulldown':               ['back', 'biceps'],
  'Seated Row':                 ['back', 'rear_delts'],
  'Cable Row':                  ['back', 'rear_delts'],
  'Barbell Row':                ['back', 'rear_delts'],
  'T-Bar Row':                  ['back', 'rear_delts'],
  'Single Arm Dumbbell Row':    ['back', 'biceps'],
  'Chest Supported Row':        ['back', 'rear_delts'],
  'Deadlift':                   ['back', 'glutes', 'hamstrings'],
  'Romanian Deadlift':          ['hamstrings', 'glutes'],
  'Rack Pull':                  ['back', 'traps'],
  'Good Morning':               ['back', 'hamstrings'],
  'Shrug':                      ['traps'],
  'Squat':                      ['quads', 'glutes'],
  'Leg Press':                  ['quads', 'glutes'],
  'Hack Squat':                 ['quads'],
  'Smith Machine Squat':        ['quads', 'glutes'],
  'Bulgarian Split Squat':      ['quads', 'glutes'],
  'Lunge':                      ['quads', 'glutes'],
  'Step Up':                    ['quads', 'glutes'],
  'Leg Extension':              ['quads'],
  'Leg Curl':                   ['hamstrings'],
  'Nordic Curl':                ['hamstrings'],
  'Hip Thrust':                 ['glutes', 'hamstrings'],
  'Calf Raise':                 ['calves'],
  'Seated Calf Raise':          ['calves'],
  'Leg Press Calf Raise':       ['calves'],
  'Bicep Curl':                 ['biceps'],
  'Hammer Curl':                ['biceps'],
  'Preacher Curl':              ['biceps'],
  'Incline Dumbbell Curl':      ['biceps'],
  'Cable Curl':                 ['biceps'],
  'Barbell Curl':               ['biceps'],
  'EZ Bar Curl':                ['biceps'],
  'Concentration Curl':         ['biceps'],
  'Tricep Pushdown':            ['triceps'],
  'Cable Tricep Pushdowns':     ['triceps'],
  'Skull Crusher':              ['triceps'],
  'Overhead Tricep Extension':  ['triceps'],
  'Dips':                       ['triceps', 'chest'],
  'Tricep Dip':                 ['triceps', 'chest'],
  'Close Grip Bench Press':     ['triceps', 'chest'],
  'Close-Grip Dumbbell Press':  ['triceps', 'chest'],
  'Plank':                      ['core'],
  'Crunch':                     ['core'],
  'Cable Crunch':               ['core'],
  'Hanging Leg Raise':          ['core'],
  'Ab Rollout':                 ['core'],
  'Russian Twist':              ['core'],
};

function getMusclesForExercise(name) {
  if (!name) return [];
  const key = Object.keys(EXERCISE_MUSCLES).find(
    (k) => k.toLowerCase() === name.toLowerCase().trim()
  );
  return key ? EXERCISE_MUSCLES[key] : [];
}

export { getMusclesForExercise };
